### ISSUE TITLE
Add progress monitors

### ISSUE THREAD

**Issue by mrbkt** [kestreltechnology/eclipse-kt-advance#19]
Advance analysis sometimes requires a noticeably long time to complete.  Both external tool and internal tool implementation should offer job progress monitors for long-running tasks.

**Comment by msiz** [comment]
I modified default checker code to run processing as a job.
This allows showing progress monitor to inform user about active process.
Used jobs instead of regular progress dialogs because they can run in the background not to annoy the user. At the same time jobs are visible in Progress view.
Will it be enough?

**Comment by mrbkt** [comment]
Yes, that’s great.

**Comment by msiz** [comment]
Closing.
